---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dns-debug.fullname" . }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "endpoints"]
  verbs: ["get", "watch", "list"]

