apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dns-debug.fullname" . }}
  labels:
    {{- include "dns-debug.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dns-debug.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dns-debug.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.debug -}}
            - name: DEBUG
              value: enabled
            {{- end }}
            - name: SERVICENAME
              value: "{{ .Values.check.servicename }}.{{ .Values.check.namespace }}.svc"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
